# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.21.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 14.0
org_name: DinamicheAziendali
org_slug: DinamicheAziendali
rebel_module_groups: []
repo_description: Tools for inventory valuation
repo_name: Stock inventory valuation
repo_slug: stock_close_period
repo_website: https://github.com/DinamicheAziendali/stock_close_period
use_pyproject_toml: false
use_ruff: false

